### PR TITLE
Add Atom One Dark Syntax file

### PR DESCRIPTION
**Pull request by andrew-pyle**
Your work with the GitHub and Tomorrow Night themes for [Spyder](https://github.com/spyder-ide/spyder) increased the number of quality themes, especially dark ones. I'd like to add one.

This [Spyder](https://github.com/spyder-ide/spyder) theme is based on the Atom One dark [UI](https://github.com/atom/one-dark-ui) and [syntax](https://github.com/atom/one-dark-syntax) theme for GitHub's Atom text editor.

I didn't dig in to the smaller syntax features, like ctrlclick, occurrence, unmatched_p, etc., so I may be able to add a few more colors and tighten up the theme.

### CODE REVIEW

**Comment by joonro** [comment]
Thank you very much for this!

**Comment by andrew-pyle** [comment]
Glad to share! Would you like me to update the README.org to reflect the addition of the Atom One dark theme? Or will you add that line?

**Comment by joonro** [comment]
Yes that would be great - I'm sorry again for the late reply.

**Comment by andrew-pyle** [comment]
I've added another Pull Request with those changes. #4

**Pull request merged**
